# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

ARG NODE_VERSION=20.11.0

FROM node:${NODE_VERSION}-alpine

# Use dev node environment by default.
ENV NODE_ENV development

WORKDIR /usr/src/app

# Copy the the source files into the image.
COPY . .
COPY .env .
COPY package.json .
COPY package-lock.json .
# Install dependencies.
RUN npm install

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD npm run dev
